# 1. Explore and clean the data

## 1.1. Import the dataset

In [1]:
import pandas as pd
import json

In [2]:
#reading the dataset 
df_cards = pd.read_csv("cards_data.csv")
df_transactions = pd.read_csv("transactions_data.csv")
df_users = pd.read_csv("users_data.csv")

In [ ]:
# import file json
with open('mcc_codes.json') as file:
    data = json.load(file)

# conert dict to dataframe
df_mcc = pd.DataFrame(list(data.items()), columns=['mcc', 'category'])

## 1.2. Explore and clean the data

### 1.2.1. df_cards

In [4]:
df_cards.shape

(6146, 13)

In [6]:
df_cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,2731,825,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,3701,825,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,42,825,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [10]:
df_cards.info()

<class 'pandas.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6146 non-null   int64
 1   client_id              6146 non-null   int64
 2   card_brand             6146 non-null   str
 3   card_type              6146 non-null   str
 4   card_number            6146 non-null   int64
 5   expires                6146 non-null   str
 6   cvv                    6146 non-null   int64
 7   has_chip               6146 non-null   str
 8   num_cards_issued       6146 non-null   int64
 9   credit_limit           6146 non-null   str
 10  acct_open_date         6146 non-null   str
 11  year_pin_last_changed  6146 non-null   int64
 12  card_on_dark_web       6146 non-null   str
dtypes: int64(6), str(7)
memory usage: 624.3 KB

In [8]:
df_cards.isnull().sum()

id                       0
client_id                0
card_brand               0
card_type                0
card_number              0
expires                  0
cvv                      0
has_chip                 0
num_cards_issued         0
credit_limit             0
acct_open_date           0
year_pin_last_changed    0
card_on_dark_web         0
dtype: int64

In [4]:
#Convert credit_limits: str to int
df_cards['credit_limit'] = pd.to_numeric(
    df_cards['credit_limit'].str.replace(r'[^0-9]', '', regex=True),
    errors='coerce'
)

In [5]:
#Convert credit_limits: str to date
df_cards['expires'] = pd.to_datetime(
    df_cards['expires'],
    format='%m/%Y'
) + pd.offsets.MonthEnd(0)

In [6]:
#Convert credit_limits: str to date
df_cards['acct_open_date'] = pd.to_datetime(
    df_cards['acct_open_date'],
    format='%m/%Y'
)

In [ ]:
df_cards['has_chip'] = df_cards['has_chip'].replace({
    'YES' : "Yes",
    'NO' : "No"
})

In [8]:
#Replace values in df_cards['has_chip']
df_cards['has_chip'] = df_cards['has_chip'].replace('No', False)

In [16]:
df_cards.head()

,id,client_id,card_brand,card_type,card_number,expires,cvv,has_chip,num_cards_issued,credit_limit,acct_open_date,year_pin_last_changed,card_on_dark_web
0,4524,825,Visa,Debit,4344676511950444,2022-12-31,623,True,2,24295,2002-09-01,2008,No
1,2731,825,Visa,Debit,4956965974959986,2020-12-31,393,True,2,21968,2014-04-01,2014,No
2,3701,825,Visa,Debit,4582313478255491,2024-02-29,719,True,2,46414,2003-07-01,2004,No
3,42,825,Visa,Credit,4879494103069057,2024-08-31,693,False,1,12400,2003-01-01,2012,No
4,4659,825,Mastercard,Debit (Prepaid),5722874738736011,2009-03-31,75,True,1,28,2008-09-01,2009,No

In [17]:
df_cards.dtypes

id                                int64
client_id                         int64
card_brand                          str
card_type                           str
card_number                       int64
expires                  datetime64[us]
cvv                               int64
has_chip                         object
num_cards_issued                  int64
credit_limit                      int64
acct_open_date           datetime64[us]
year_pin_last_changed             int64
card_on_dark_web                    str
dtype: object

### 1.2.2. df_transactions

In [18]:
df_transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [19]:
df_transactions.dtypes

id                  int64
date                  str
client_id           int64
card_id             int64
amount                str
use_chip              str
merchant_id         int64
merchant_city         str
merchant_state        str
zip               float64
mcc                 int64
errors                str
dtype: object

In [ ]:
#Check if the columns have null values.
df_transactions.isnull().sum()

id                       0
date                     0
client_id                0
card_id                  0
amount                   0
use_chip                 0
merchant_id              0
merchant_city            0
merchant_state     1563700
zip                1652706
mcc                      0
errors            13094522
dtype: int64

In [ ]:
df_transactions[df_transactions['merchant_state'].isnull()]

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
7,7475335,2010-01-01 00:14:00,1684,2140,$26.46,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
8,7475336,2010-01-01 00:21:00,335,5131,$261.58,Online Transaction,50292,ONLINE,NaN,NaN,7801,NaN
18,7475346,2010-01-01 00:34:00,394,4717,$26.04,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
24,7475353,2010-01-01 00:43:00,301,3742,$10.17,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
26,7475356,2010-01-01 00:45:00,566,3439,$16.86,Online Transaction,16798,ONLINE,NaN,NaN,4121,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13305879,23761832,2019-10-31 23:22:00,1556,2972,$17.65,Online Transaction,88459,ONLINE,NaN,NaN,5311,NaN
13305880,23761833,2019-10-31 23:22:00,1797,5660,$34.81,Online Transaction,15143,ONLINE,NaN,NaN,4784,NaN
13305888,23761843,2019-10-31 23:33:00,1069,5167,$59.71,Online Transaction,39021,ONLINE,NaN,NaN,4784,NaN
13305897,23761853,2019-10-31 23:39:00,1422,5696,$694.30,Online Transaction,70268,ONLINE,NaN,NaN,4722,NaN
13305911,23761869,2019-10-31 23:56:00,1766,2066,$12.80,Online Transaction,39261,ONLINE,NaN,NaN,5815,NaN

In [10]:
df_transactions[df_transactions['merchant_state'].isnull()].isnull().sum()

id                      0
date                    0
client_id               0
card_id                 0
amount                  0
use_chip                0
merchant_id             0
merchant_city           0
merchant_state    1563700
zip               1563700
mcc                     0
errors            1528138
dtype: int64

In [ ]:
#Replace null valuess
df_transactions.fillna({
    'merchant_state': 'Online',
    'zip':'Online'
}, inplace=True)

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
13305910,23761868,2019-10-31 23:56:00,1718,2379,$1.11,Chip Transaction,86438,West Covina,CA,91792.0,5499,NaN
13305911,23761869,2019-10-31 23:56:00,1766,2066,$12.80,Online Transaction,39261,ONLINE,Online,Online,5815,NaN
13305912,23761870,2019-10-31 23:57:00,199,1031,$40.44,Swipe Transaction,2925,Allen,TX,75002.0,4900,NaN
13305913,23761873,2019-10-31 23:58:00,1986,5443,$4.00,Chip Transaction,46284,Daly City,CA,94014.0,5411,NaN
13305914,23761874,2019-10-31 23:59:00,489,5697,$12.88,Chip Transaction,24658,Greenbrier,TN,37073.0,5921,NaN

In [12]:
df_transactions['merchant_city'] = df_transactions['merchant_city'].replace('ONLINE', 'Online')

In [ ]:
df_transactions['errors'] = df_transactions['errors'].fillna('Successful transaction')

In [28]:
df_transactions['errors'].unique()

<StringArray>
[                             'Successful transaction',
                                    'Technical Glitch',
                                      'Bad Expiration',
                                     'Bad Card Number',
                                'Insufficient Balance',
                                             'Bad PIN',
                                             'Bad CVV',
                                         'Bad Zipcode',
               'Insufficient Balance,Technical Glitch',
                        'Bad PIN,Insufficient Balance',
                            'Bad PIN,Technical Glitch',
                     'Bad Expiration,Technical Glitch',
                      'Bad Card Number,Bad Expiration',
                'Bad Card Number,Insufficient Balance',
                 'Bad Expiration,Insufficient Balance',
                             'Bad Card Number,Bad CVV',
                            'Bad CVV,Technical Glitch',
                              'Bad Expiration,Bad CVV',
                        'Bad CVV,Insufficient Balance',
                    'Bad Card Number,Technical Glitch',
                    'Bad Zipcode,Insufficient Balance',
 'Bad Card Number,Bad Expiration,Insufficient Balance',
                        'Bad Zipcode,Technical Glitch']
Length: 23, dtype: str

In [15]:
#Convert date: str to date
df_transactions['date'] = pd.to_datetime(
    df_transactions['date'],
    errors='coerce'
)

In [16]:
#Convert amount: str to int
df_transactions['amount'] = pd.to_numeric(
    df_transactions['amount'].str.replace(r'[^0-9.-]', '', regex=True),
    errors='coerce'
)

In [42]:
df_transactions.dtypes

id                         int64
date              datetime64[us]
client_id                  int64
card_id                    int64
amount                   float64
use_chip                     str
merchant_id                int64
merchant_city                str
merchant_state               str
zip                       object
mcc                        int64
errors                       str
dtype: object

In [30]:
df_transactions.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,Successful transaction
1,7475328,2010-01-01 00:02:00,561,4575,14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,Successful transaction
2,7475329,2010-01-01 00:02:00,1129,102,80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,Successful transaction
3,7475331,2010-01-01 00:05:00,430,2860,200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,Successful transaction
4,7475332,2010-01-01 00:06:00,848,3915,46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,Successful transaction

In [44]:
df_transactions.isnull().sum()

id                0
date              0
client_id         0
card_id           0
amount            0
use_chip          0
merchant_id       0
merchant_city     0
merchant_state    0
zip               0
mcc               0
errors            0
dtype: int64

### 1.2.3. df_users

In [45]:
df_users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,$29278,$59696,$127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,$37891,$77254,$191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,$22681,$33483,$196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,$163145,$249925,$202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,$53797,$109687,$183855,675,1

In [46]:
df_users.dtypes

id                     int64
current_age            int64
retirement_age         int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
latitude             float64
longitude            float64
per_capita_income        str
yearly_income            str
total_debt               str
credit_score           int64
num_credit_cards       int64
dtype: object

In [47]:
df_users.isnull().sum()

id                   0
current_age          0
retirement_age       0
birth_year           0
birth_month          0
gender               0
address              0
latitude             0
longitude            0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
dtype: int64

In [48]:
df_users.gender.unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [17]:
#Convert data type str to int
df_users['yearly_income'] = pd.to_numeric(
    df_users['yearly_income'].str.replace(r'[^0-9]', '', regex=True),
    errors='coerce'
)

In [18]:
#Convert data type str to int
df_users.total_debt = pd.to_numeric(
    df_users['total_debt'].str.replace(r'[^0-9]', '', regex=True),
    errors='coerce'
)

In [19]:
#Convert data type str to int
df_users['per_capita_income'] = pd.to_numeric(
    df_users['per_capita_income'].str.replace(r'[^0-9]', '',regex=True),
    errors='coerce'
)

In [52]:
df_users.dtypes

id                     int64
current_age            int64
retirement_age         int64
birth_year             int64
birth_month            int64
gender                   str
address                  str
latitude             float64
longitude            float64
per_capita_income      int64
yearly_income          int64
total_debt             int64
credit_score           int64
num_credit_cards       int64
dtype: object

In [53]:
df_users.head()

,id,current_age,retirement_age,birth_year,birth_month,gender,address,latitude,longitude,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards
0,825,53,66,1966,11,Female,462 Rose Lane,34.15,-117.76,29278,59696,127613,787,5
1,1746,53,68,1966,12,Female,3606 Federal Boulevard,40.76,-73.74,37891,77254,191349,701,5
2,1718,81,67,1938,11,Female,766 Third Drive,34.02,-117.89,22681,33483,196,698,5
3,708,63,63,1957,1,Female,3 Madison Street,40.71,-73.99,163145,249925,202328,722,4
4,1164,43,70,1976,9,Male,9620 Valley Stream Drive,37.76,-122.44,53797,109687,183855,675,1

# 2. Upload data to the server

In [54]:
import sqlalchemy
import pymysql

print(sqlalchemy.__version__)
print(pymysql.__version__)

2.0.49
1.4.6

## Load dataset into the database

In [ ]:
from sqlalchemy import create_engine

#Connection
engine = create_engine(
    "mysql+pymysql://root:insertyourpassword@localhost:3306/dataset_project_banking"
)

df_cards.to_sql(
    name="dim_cards",        # input table name
    con=engine,
    if_exists="append", 
    index=False
)

print("Load thành công!")

Load thành công!

In [ ]:
engine = create_engine(
    "mysql+pymysql://root:insertyourpassword@localhost:3306/dataset_project_banking"
)

def load_to_mysql(df, table_name, if_exists="append"):
    df = df.where(pd.notnull(df), None)
    df.columns = df.columns.str.replace(" ", "_")

    df.to_sql(
        name=table_name,
        con=engine,
        if_exists=if_exists,
        index=False,
        chunksize=1000
    )

    print(f"✅ Loaded vào bảng: {table_name}")

In [ ]:
load_to_mysql(df_transactions, "fact_transactions")
load_to_mysql(df_users, "dim_users")
load_to_mysql(df_mcc, "dim_mcc")

✅ Loaded vào bảng: fact_transactions
✅ Loaded vào bảng: dim_users
✅ Loaded vào bảng: dim_mcc